################## Categories ##################

POST http://localhost:5212/v1/categories
Content-Type: application/json

{
    "name": null
}

###
GET http://localhost:5212/v1/categories?page=1&size=10&desc=false&search=

###
GET http://localhost:5212/v1/categories/7

###
PUT http://localhost:5212/v1/categories/6
Content-Type: application/json

{
    "name": ""
}

###
DELETE http://localhost:5212/v1/categories/11