################## Authentication ##################

POST http://localhost:5212/v1/auth/signup
Content-Type: application/json

{
    "firstName": "Reza",
    "lastName": "Asghari",
    "email": "mehmet@gmail.com",
    "phoneNumber": "+905368375805",
    "password": "159357"
}

###
POST http://localhost:5212/v1/auth/login
Content-Type: application/json

{
    "email": "mehmet@gmail.com",
    "password": "159357"
}

################## Categories ##################

POST http://localhost:5212/v1/categories
Content-Type: application/json

{
    "name": null
}

###
GET http://localhost:5212/v1/categories?page=1&size=10&desc=false&search=

###
GET http://localhost:5212/v1/categories/7

###
PUT http://localhost:5212/v1/categories/6
Content-Type: application/json

{
    "name": ""
}

###
DELETE http://localhost:5212/v1/categories/11